### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by lzk950310** [uditkarode/AbleMusicPlayer#125]
According to your code, why is this error in my own code.Is there a solution? Thank you

**Comment by uditkarode** [comment]
I don't understand, can you provide more information with context?

**Comment by bluejeans117** [comment]
Ooo ganja ganja

**Comment by bluejeans117** [comment]
> According to your code, why is this error in my own code.Is there a solution? Thank you

@lzk950310 provide error logs, steps to reproduce, device/OS info.. you know the drill :)

**Comment by lzk950310** [comment]
> I don't understand, can you provide more information with context?

Sorry, I didn't make it clear.When I use ffmpeg- mobile.aar When this error occurs, convert the audio to .mp3

**Comment by bluejeans117** [comment]
> > I don't understand, can you provide more information with context?
> 
> Sorry, I didn't make it clear.When I use ffmpeg- mobile.aar When this error occurs, convert the audio to .mp3

Again, try  https://github.com/uditkarode/AbleMusicPlayer/issues/125#issuecomment-748498250

**Comment by lzk950310** [comment]
> I don't understand, can you provide more information with context?
This is the log

I/mobile-ffmpeg: Loading mobile-ffmpeg.
I/mobile-ffmpeg: Loaded mobile-ffmpeg-custom-arm64-v8a-4.4-lts-20201029.
D/mobile-ffmpeg: Callback thread started.
I/mobile-ffmpeg: ffmpeg version v4.4-dev-416
     Copyright (c) 2000-2020 the FFmpeg developers
      built with Android (6454773 based on r365631c2) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489587874b2a325e7a516b99d838599c6f) (based on LLVM 9.0.8svn)
      configuration: --cross-prefix=aarch64-linux-android- --sysroot=/home/udit/AndroidSDK/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/udit/ffmpeg_work/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android21-clang --cxx=aarch64-linux-android21-clang++ --extra-libs='-L/home/udit/ffmpeg_work/mobile-ffmpeg/prebuilt/android-arm64/cpu-features/lib -lndk_compat' --target-os=android --disable-everything --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-network --disable-autodetect --enable-small --enable-libshine --enable-decoder='libshine,mp3,webm,matroska,opus,vorbis' --enable-demuxer='mp3,webm,matroska,opus,vorbis' --enable-encoder='libshine,matroska,webm,opus,vorbis' --enable-muxer='mp3,matroska,opus,webm,vorbis' --enable-protocol=file --enable-filter=aresample --enable-small --disable-debug --enable-lto --disable-sdl2 --disable-zlib
      libavutil      56. 55.100 / 56. 55.100
      libavcodec     58. 96.100 / 58. 96.100
      libavformat    58. 48.100 / 58. 48.100
      libavdevice    58. 11.101 / 58. 11.101
      libavfilter     7. 87.100 /  7. 87.100
      libswscale      5.  8.100 /  5.  8.100
      libswresample   3.  8.100 /  3.  8.100
E/mobile-ffmpeg: /storage/emulated/0/Music/Alan Walker Faded.m4a: Invalid data found when processing input

**Comment by uditkarode** [comment]
Able variant doesn't include m4a support, since it's not required on Able. I recommend you to use the original library by tanersener.

**Comment by lzk950310** [comment]
> Able variant doesn't include m4a support, since it's not required on Able. I recommend you to use the original library by tanersener.

I see , thanks
