### ISSUE TITLE
Wrong highlighted selected song

### ISSUE THREAD

**Issue by Charlieras262** [uditkarode/AbleMusicPlayer#16]
![Screenshot_20200703-011945_Able](https://user-images.githubusercontent.com/44990120/86444004-55155380-bccd-11ea-9e3b-82b698c57e17.jpg)

Info:
Device: Samsung Galaxy A70
Android version: 10.0
App version: CataliticClaws(1) (8622c2b8)

Steps to reproduce the issue:

1. Select a song position > 1
2. Select the first song

**Comment by chtgupta** [comment]
Thanks for reporting. Will see to it.

**Comment by captain-nemo1** [comment]
In SongAdapter in onBindViewHolder(), in the condition for color check, the index 0 was being ignored as the check was (currentIndex > 0). I have added the Fix. Wait for Udit to merge it.

**Comment by uditkarode** [comment]
This has been fixed :) :1st_place_medal:
