### ISSUE TITLE
Can't open the app

### ISSUE THREAD

**Issue by Axtronaut** [uditkarode/AbleMusicPlayer#205]
My device is a **armeabi-V7 (ARM)** and every time I try to open the application it gives an error.
He installed normal, the only problem is to open.

![Screenshot_20211006-202514.jpeg](https://user-images.githubusercontent.com/78208816/136296969-1965da17-e129-4b79-8286-55d1ef319867.jpeg)

**Comment by SoreAMan** [comment]
I found a solution. I just gave the app storage permissions and it worked!
