### ISSUE TITLE
how to download the app

### ISSUE THREAD

**Issue by vikasdigital** [uditkarode/AbleMusicPlayer#76]
There are no assests to download the app

**Comment by uditkarode** [comment]
https://github.com/uditkarode/AbleMusicPlayer/tree/builds

here, you'll find two files. you can download the file that's for your device's architecture. close this if you can figure it out.
you can also get to that link through uditkarode.github.io/able

**Comment by uditkarode** [comment]
I've added the link and necessary resources to the project's README

**Comment by vikasdigital** [comment]
thanks sir for help
