### ISSUE TITLE
not play after search again

### ISSUE THREAD

**Issue by toneytang** [uditkarode/AbleMusicPlayer#89]
installed Arm64 version. 

after search, click the playlist, click play, it is working. 

then search again, click the playlist, click play. It still play the previous list not change to new list.

Tried to pause the playing and click the new playlist, still not working.

**Comment by toneytang** [comment]
stopped the app and restart, it can search for once again.

**Comment by uditkarode** [comment]
yeah, something's wrong with playlists right now. I'm looking into it.
